package online.shop.java.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name = "products")
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // For SERIAL
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String category;

    @Column(nullable = false)
    private BigDecimal price;

    @Column(nullable = false)
    private BigDecimal discount;

    // This will not be insertable/updatable since it's a generated column
    @Column(name = "discounted_price", insertable = false, updatable = false)
    private BigDecimal discountedPrice;

    @Column(nullable = false)
    private int quantity;

    @Column(name = "expiry_date")
    private LocalDate expiryDate;

    @Column(insertable = false, updatable = false)
    private String available; // Yes / No

    // Getters and setters

    public Product() {}

    // Optional: full constructor (without autogenerated fields)
    public Product(String name, String category, BigDecimal price, BigDecimal discount,
                   int quantity, LocalDate expiryDate) {
        this.name = name;
        this.category = category;
        this.price = price;
        this.discount = discount;
        this.quantity = quantity;
        this.expiryDate = expiryDate;
    }

    // Getters and Setters...
    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }

    public String getCategory() { return category; }

    public void setCategory(String category) { this.category = category; }

    public BigDecimal getPrice() { return price; }

    public void setPrice(BigDecimal price) { this.price = price; }

    public BigDecimal getDiscount() { return discount; }

    public void setDiscount(BigDecimal discount) { this.discount = discount; }

    public BigDecimal getDiscountedPrice() { return discountedPrice; }

    public int getQuantity() { return quantity; }

    public void setQuantity(int quantity) { this.quantity = quantity; }

    public LocalDate getExpiryDate() { return expiryDate; }

    public void setExpiryDate(LocalDate expiryDate) { this.expiryDate = expiryDate; }

    public String getAvailable() { return available; }
}
